# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Settings -> Actions -> General でWorkflow permissionsを設定する。
# ◎Read and write permissions

name: Evaluate Result

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    create-leaderboard:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
                  architecture: "x64"
            - name: Install pip
              run: pip install pip --upgrade
            - name: Install dependencies
              run: pip install -r '.github/workflows/requirements.txt'
            - name: Run Python
              run: python '.github/workflows/evaluation.py'
            - name: Configure Git
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
            - name: Check for changes and Commit
              run: |
                  if [ -z "$(git status --porcelain)" ]; then
                    echo "No changes to commit."
                  else
                    echo "Changes detected."
                    git add .
                    git commit -m "Auto create result - $(TZ=JST-9 date +%Y-%m-%d)"
                    git push origin master
                  fi
